sudo: required
services:
    - docker

before_install:
    - docker build -t kaushikppe/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kaushikppe/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-React"
    env: "Docker-React-env"
    bucket_name: "elasticbeanstalk-us-east-2-377514948958"
    bucket_path: "Docker-React"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY